name: NetworkTests
on:
  push:
    branches:
      - main
      - Feature1-Network-Analysis
  pull_request:
    branches:
      - main
      - Feature1-Network-Analysis

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install pytest

      - name: Run Tests
        run: pytest test_my_notebook1.py
